//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rustic.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rustic.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить.
        /// </summary>
        public static string LoginView_Auto {
            get {
                return ResourceManager.GetString("LoginView_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string LoginView_Ok {
            get {
                return ResourceManager.GetString("LoginView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершенные задачи.
        /// </summary>
        public static string ShellView_AcceptedTooltip {
            get {
                return ResourceManager.GetString("ShellView_AcceptedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить задачу.
        /// </summary>
        public static string ShellView_AcceptTaskTooltip {
            get {
                return ResourceManager.GetString("ShellView_AcceptTaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить задачу.
        /// </summary>
        public static string ShellView_AddTaskTooltip {
            get {
                return ResourceManager.GetString("ShellView_AddTaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все задачи.
        /// </summary>
        public static string ShellView_AllTooltip {
            get {
                return ResourceManager.GetString("ShellView_AllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группировать задачи.
        /// </summary>
        public static string ShellView_GroupTask {
            get {
                return ResourceManager.GetString("ShellView_GroupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключиться к серверу.
        /// </summary>
        public static string ShellView_LoginTooltip {
            get {
                return ResourceManager.GetString("ShellView_LoginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключиться от сервера.
        /// </summary>
        public static string ShellView_LogoutTooltip {
            get {
                return ResourceManager.GetString("ShellView_LogoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string ShellView_RefreshTooltip {
            get {
                return ResourceManager.GetString("ShellView_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группировать задачи.
        /// </summary>
        public static string ShellView_ShowByGroupTooltip {
            get {
                return ResourceManager.GetString("ShellView_ShowByGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покзывать завершенные.
        /// </summary>
        public static string ShellView_ShowIsDoneTooltip {
            get {
                return ResourceManager.GetString("ShellView_ShowIsDoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно установить соединение с сервером: .
        /// </summary>
        public static string ShellViewModel_ConnectError {
            get {
                return ResourceManager.GetString("ShellViewModel_ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая задача.
        /// </summary>
        public static string ShellViewModel_NewTask {
            get {
                return ResourceManager.GetString("ShellViewModel_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключены к серверу.
        /// </summary>
        public static string ShellViewModel_StatusConnected {
            get {
                return ResourceManager.GetString("ShellViewModel_StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создается задача, ожидайте....
        /// </summary>
        public static string ShellViewModel_StatusCreating {
            get {
                return ResourceManager.GetString("ShellViewModel_StatusCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключены.
        /// </summary>
        public static string ShellViewModel_StatusDisconnected {
            get {
                return ResourceManager.GetString("ShellViewModel_StatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется операция....
        /// </summary>
        public static string ShellViewModel_StatusOperation {
            get {
                return ResourceManager.GetString("ShellViewModel_StatusOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен авторизации не получен.
        /// </summary>
        public static string TokenNotExist {
            get {
                return ResourceManager.GetString("TokenNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
